"""empty message

Revision ID: 95190fc568fe
Revises: 1ba604279901
Create Date: 2022-07-10 15:06:47.896269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95190fc568fe'
down_revision = '1ba604279901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
